trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Download and unzip Terraform
    wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
    unzip terraform_0.12.24_linux_amd64.zip
    # Move Terraform to a folder which is in $PATH
    sudo mv terraform /usr/local/bin/
  displayName: Install Terraform

- script: |
    # Download and unzip tflint
    curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip
    unzip tflint.zip
    # Move tflint to a folder which is in $PATH
    sudo mv tflint /usr/local/bin/
    rm tflint.zip
  displayName: Install tflint

- script: make validate
  displayName: 'Validate terraform'

- script: make format
  displayName: 'Ensure terraform format'

- script: make validate_tests
  displayName: 'Validate tests'

- script: make format_tests
  displayName: 'Ensure terraform format for tests'

- script: make validate_examples
  displayName: 'Validate examples'

- script: make format_examples
  displayName: 'Ensure terraform format for examples'

- script: tflint
  displayName: 'Check Terraform configurations with tflint'